### PR TITLE
Bumps version to 5.14.23

### PR DESCRIPTION
**Pull request by gnkidwell**
Added unlock and lock of all install-unifi.sh packages. This prevents pkg upgrade, or OPNSense updates to reinstall previously installed packages, which in turn break the UniFi controller.

### CODE REVIEW

**Review by gnkidwell — COMMENTED** [review]
I have confirmed the addition of the pkg unlock and pkg lock commands to keep the UniFi controller functional during installation and after. The one biggest concern was when running pkg upgrade, some packages may be marked for reinstallation. This can break the UniFi controller, by locking the packages at the end of adding them we ensure pkg upgrade and OPNSense cannot reinstall or update the packages.

**Comment by tong2x** [comment]
will this be upgraded in the future by the Unifi install upgrade
assuming there is an upgrade in the future?

**Comment by gnkidwell** [comment]
> will this be upgraded in the future by the Unifi install upgrade
> assuming there is an upgrade in the future?

Not sure what your are asking here. I did add the package unlock and lock patch to all of the current install links. 5.14.23 is listed for people that do not want to upgrade to version 6. So now all links will not cause issues with any updates for OPNSense.

**Comment by tong2x** [comment]
re installed build 31 only minor error (pfsense base.tzt file normal since im on opnsense).
will try out in your future build release

**Pull request merged**
